name: base
channels:
  - main
  - conda-forge
dependencies:
  - conda-build
  - pytest
  - ipykernel
  - xarray
  - pandas
  - numpy
  - matplotlib
  - netcdf4
  - glob2
  - validators
  - cartopy
  - erddapy
  - siphon
